/**
 * Centralized Application State Types for Telemeister
 *
 * This file re-exports types from the auto-generated bot-state-types.ts.
 * Do not edit this file - use npm run state:sync to regenerate types.
 */

export type { AppStates, StateTransitions } from '../bot-state-types.js';
