// Auto-generated by telemeister state:sync - DO NOT EDIT

export type AppStates = 'idle' | 'menu' | 'poll' | 'welcome';

export type StateTransitions = {
  idle: 'welcome' | void;
  menu: 'poll' | 'welcome' | void;
  poll: 'menu' | void;
  welcome: 'menu' | void;
};

export type IdleTransitions = Promise<StateTransitions['idle']>;
export type MenuTransitions = Promise<StateTransitions['menu']>;
export type PollTransitions = Promise<StateTransitions['poll']>;
export type WelcomeTransitions = Promise<StateTransitions['welcome']>;
